# Generated by Django 5.2.4 on 2025-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtestquestion',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
