# Generated by Django 5.2.4 on 2025-07-28 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_test', '0002_codingtestquestion_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='codingtestsubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='codingtestsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='codingtestsubmission',
            name='language',
        ),
        migrations.RemoveField(
            model_name='codingtestsubmission',
            name='status',
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='compile_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='expected_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='language_id',
            field=models.IntegerField(default=54),
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='status_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='status_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='stdin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codingtestsubmission',
            name='stdout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingtestsubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding_test.codingtestquestion'),
        ),
        migrations.AlterField(
            model_name='codingtestsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
