# Generated by Django 5.2.4 on 2025-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
