# Generated by Django 5.2.4 on 2025-07-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quizattempt_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='option_a',
            new_name='option_A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_b',
            new_name='option_B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_c',
            new_name='option_C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option_d',
            new_name='option_D',
        ),
    ]
