# Generated by Django 5.2.4 on 2025-07-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='question_text',
        ),
    ]
