# Generated by Django 5.2.4 on 2025-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_interviewquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_text',
            field=models.JSONField(default=dict),
        ),
    ]
