# Generated by Django 5.2.4 on 2025-07-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='score',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
